"""add activity table

Revision ID: 36223ec74ca3
Revises: 6982f0c59fb6
Create Date: 2026-03-16 16:01:08.804387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36223ec74ca3'
down_revision: Union[str, None] = '6982f0c59fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###
