"""add verification and reset token fields to user

Revision ID: 699f0eec7da0
Revises: c03381bb89f0
Create Date: 2026-03-06 15:32:02.145866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699f0eec7da0'
down_revision: Union[str, None] = 'c03381bb89f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
