"""add image fields to profile event community post message

Revision ID: c03381bb89f0
Revises: f204539ca33d
Create Date: 2026-03-05 17:24:49.316920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03381bb89f0'
down_revision: Union[str, None] = 'f204539ca33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('communities', sa.Column('cover_image_public_id', sa.String(length=500), nullable=True))
    op.add_column('community_posts', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('community_posts', sa.Column('image_public_id', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('cover_image_public_id', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('image_public_id', sa.String(length=500), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('profiles', sa.Column('avatar_public_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_public_id')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'image_public_id')
    op.drop_column('messages', 'image_url')
    op.drop_column('events', 'cover_image_public_id')
    op.drop_column('events', 'cover_image_url')
    op.drop_column('community_posts', 'image_public_id')
    op.drop_column('community_posts', 'image_url')
    op.drop_column('communities', 'cover_image_public_id')
    op.drop_column('communities', 'cover_image_url')
    # ### end Alembic commands ###
