from enum import Enum

class ActivityType(str, Enum):
    JOINED_COMMUNITY = "JOINED_COMMUNITY"
    LEFT_COMMUNITY = "LEFT_COMMUNITY"
    CREATED_POST = "CREATED_POST"
    RSVP_EVENT = "RSVP_EVENT"
    CANCELLED_RSVP = "CANCELLED_RSVP"
    CONNECTED_WITH_USER = "CONNECTED_WITH_USER"
    STARTED_MENTORSHIP = "STARTED_MENTORSHIP"
    SENT_MESSAGE = "SENT_MESSAGE"